services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgresUser
      - POSTGRES_PASSWORD=postgresPw
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: