name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  AWS_REGION: us-west-2
  LAMBDA_FUNCTION_NAME: Rentminder
  DOTNET_VERSION: "8.0.202"
  NODE_VERSION: "18.14.1"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      # Install frontend dependencies and build
      - name: Install and build frontend
        working-directory: ./Client
        run: |
          npm ci
          npm run build

      # Verify wwwroot directory exists
      - name: Ensure wwwroot directory exists
        working-directory: ./API
        run: mkdir -p wwwroot

      # Build and publish .NET project
      - name: Build and publish .NET project
        working-directory: ./API
        run: |
          dotnet restore
          dotnet publish -c Release -o ./publish

      # Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # Deploy to Lambda
      - name: Deploy to Lambda
        working-directory: ./API/publish
        run: |
          zip -r ../lambda-deployment.zip .
          aws lambda update-function-code --function-name ${{ env.LAMBDA_FUNCTION_NAME }} --zip-file fileb://../lambda-deployment.zip

      # Update Lambda environment variables
      - name: Update Lambda environment
        run: |
          aws lambda update-function-configuration \
            --function-name ${{ env.LAMBDA_FUNCTION_NAME }} \
            --runtime dotnet8 \
            --handler API \
            --memory-size 256 \
            --timeout 500 \
